### ISSUE TITLE
Serene Seasons incompatibility

### ISSUE THREAD

**Issue by rver38** [iPortalTeam/ImmersivePortalsModForForge#170] opened 2024-09-09 19:11 UTC
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

No

### Forge Version

43.4.0

### ImmersivePortals Version

2.3.7-mc1.19.2

### Latest Log

https://gist.github.com/rver38/d2da9714873fefce5dade281c310b6f4

### Crash Report (if applicable)

https://gist.github.com/rver38/b278d073ea284d76ef785beaa518a7e7

### Steps to Reproduce

1. Create a new modpack
2. Add Immersive Portals For Forge
3. Add [Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) by TheAdubbz, Forstride

### What You Expected

I was trying to generate a world to test if the modpack was working.

### What Happened Instead

Game kept crashing before world generation even started.

### Additional Details

Happens with and without Dimension Stack enabled. Other mods like [Biomes O´Plenty](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty) by the same developers work fine.

### Please Read and Confirm The Following

- [x] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment] 2024-09-09 20:46
Duplicate of #76

**Closed as not planned by Nick1st** 2024-09-09 20:46 UTC
Labels: bug, duplicate, Mod Compatibility, Unsupported MC-Version, 1.19.2
