### ISSUE TITLE
F3 Not Working

### ISSUE THREAD

**Issue by GhoulGeek** [iPortalTeam/ImmersivePortalsModForForge#169] opened 2024-07-28 16:55 UTC
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

43.4.0

### ImmersivePortals Version

2.3.7-mc1.19.2-forge.jar

### Latest Log

latest.log

### Steps to Reproduce

1. Install a 1.19.2 profile for Java
2. Choose Forge 43.4.0
3. Install Immersive Portals
4. Press F3 in-game

### What You Expected

Usually when you press F3, a debug menu opens in Minecraft. This also happens with the Fabric version of Immersive Portals, so I know it's not a problem with the mod specifically. 

### What Happened Instead

Instead of opening a debug menu, the game just switches my cursor to the F3 cursor. As far as I know this only works in Forge 1.19.2. If anyone could help it would be great!

### Additional Details

I am using Windows 10, and I have like 30 mods installed(including Immersive Portals). This issue occurs as well with only the mod installed, so as far as I know it's not a compatibility issue. I tried uninstalling Immersive Portals and the debug menu works.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment] 2024-11-10 18:50
Duplicate of #160

**Closed as not planned by Nick1st** 2024-11-10 18:50 UTC
Labels: bug, duplicate, 1.19.2
