### ISSUE TITLE
makes forge fail to load on start up.

### ISSUE THREAD

**Issue by Horsemun691** [iPortalTeam/ImmersivePortalsModForForge#113] opened 2023-05-12 20:44 UTC
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

43.2.0

### ImmersivePortals Version

 immersive-portals-2.3.5-mc1.19.2-forge.jar

### Latest Log

https://gist.github.com/Horsemun691/bb1200dceeb54c1d58b178f293de3ca6

### Crash Report (if applicable)

https://gist.github.com/Horsemun691/bb1200dceeb54c1d58b178f293de3ca6

### Steps to Reproduce

run game
game crashes
![image](https://github.com/iPortalTeam/ImmersivePortalsModForForge/assets/133430448/05812227-eaaa-4c40-a2ee-84243bd0c028)

### What You Expected

game to start

### What Happened Instead

game crashed

### Additional Details

If its just one mod causing it please tell me

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment] 2023-06-03 11:10
Duplicate of #21

**Closed as not planned by Nick1st** 2023-06-03 11:10 UTC
Labels: bug, duplicate
