### ISSUE TITLE
Crawling through 1*1 nether portals kicks you out of crawl state when traveling through

### ISSUE THREAD

**Issue by ScoutTheSaneless** [iPortalTeam/ImmersivePortalsModForForge#2] opened 2022-08-18 23:01 UTC
### According to your testing, does the issue occur with ONLY Immersive Portals mod?

Yes

### Forge Version

40.1.60

### ImmersivePortals Version

1.4.9-mc1.18.2

### Latest Log

https://gist.github.com/ChaosDogG/85320ffdcb9dffef7024a20f68f3b58a

### Steps to Reproduce

1. Build 1*1 nether portal and light
2. Equip Elytra or place trapdoor to enter crawl state in overworld
3. Cross portal and get kicked out of crawl state for whatever reason which could cause suffication

### What You Expected

I expected to be able to seamlessly crawl through the 1*1 portal without being kicked out of crawl state

### What Happened Instead

When I entered/exited the Nether, I was put into standing state when I clearly had a block above my head that should keep me in crawl

### Additional Details

The method to get into crawl state doesn't really matter, swimming first, gliding, trapdoor/piston, just so long as you get into crawl state before you cross the tiny portal

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [x] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment] 2022-08-19 08:50
Possible duplicate of https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1161

**Comment by qouteall** [comment] 2023-01-17 12:59
This is already fixed in the latest Fabric version.

**Closed as completed** 2023-03-29 18:40 UTC
Labels: bug, fabric, Fixed in higher MC Version
