### ISSUE TITLE
Game gets stuck on loading Terrain

### ISSUE THREAD

**Issue by KellCon** [iPortalTeam/ImmersivePortalsModForForge#125] opened 2023-06-30 01:04 UTC
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

1.19.2

### ImmersivePortals Version

2.3.5

### Latest Log

No errors

### Crash Report (if applicable)

none

### Steps to Reproduce

Turn on lightVanillaNetherPortalWhenCrouching": true,
make a portal
go into portal

### What You Expected

get the the other side

### What Happened Instead

when you turn on the setting lightVanillaNetherPortalWhenCrouching": true, and enter a portal thats not immersive, the game gets stuck on loading terrian and you have to restart your game, and its not just me same with my friends.

### Additional Details

this is all I know

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment] 2023-07-01 13:55
Duplicate of #66.

**Closed as not planned** 2023-07-01 13:55 UTC
Labels: bug, duplicate
