### ISSUE TITLE
Crash while trying to register a key

### ISSUE THREAD

**Issue by GASPOUR** [iPortalTeam/ImmersivePortalsModForForge#127] opened 2023-07-04 13:22 UTC
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

43.2.0

### ImmersivePortals Version

2.3.5-mc1.19.2

### Latest Log

https://gist.github.com/GASPOUR/0076f706ed9af28a499e2893e348575c

### Crash Report (if applicable)

https://gist.github.com/GASPOUR/6456bed4e77a35265f14d291f5e47ff1

### Steps to Reproduce

1. install immersive portal
2. Launch the modpack
3. crash.

### What You Expected

The game launch

### What Happened Instead

The game crash

### Additional Details

While exploring the log it seems immersive portal try to register a key and can't.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment] 2023-07-04 17:30
Duplicate of #123

**Closed as not planned by Nick1st** 2023-07-04 17:30 UTC
Labels: bug, duplicate
