### ISSUE TITLE
Pluto Causes A Crash on World Load

### ISSUE THREAD

**Issue by Mysticpasta1** [iPortalTeam/ImmersivePortalsModForForge#95] opened 2023-03-28 13:00 UTC
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

No

### Forge Version

43.2.6

### ImmersivePortals Version

2.3.3-mc1.19.2

### Latest Log

https://gist.github.com/Mysticpasta1/30f2077e1d6637a095b39f944acf4ec4

### Crash Report (if applicable)

https://gist.github.com/Mysticpasta1/8c8039898f78accffea967a7a1aa22a5

### Steps to Reproduce

1. Install IP for Forge, Cloth Config, and Pluto in the same mods folder
2. Start game and make a Default new world on Creative
3. Wait for the Crash to occur

### What You Expected

It not to crash on world creation

### What Happened Instead

It crashed on world creation with this error

`Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/server/level/ChunkMap::sendChunkDataPackets$beSmart with priority 1000 cannot inject into net/minecraft/server/level/ChunkMap::m_183760_(Lnet/minecraft/server/level/ServerPlayer;Lorg/apache/commons/lang3/mutable/MutableObject;Lnet/minecraft/world/level/chunk/LevelChunk;)V merged by qouteall.imm_ptl.core.mixin.common.chunk_sync.MixinChunkMap_C with priority 1100 [PREINJECT Applicator Phase -> pluto.mixins.json:network.avoidwork.ChunkMapMixin -> Prepare Injections ->  -> handler$zga000$sendChunkDataPackets$beSmart(Lnet/minecraft/server/level/ServerPlayer;Lorg/apache/commons/lang3/mutable/MutableObject;Lnet/minecraft/world/level/chunk/LevelChunk;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]`

### Additional Details

It is a server ticking error on a mixin crash

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Theisgood** [comment] 2023-04-04 22:18
Wow I actually was trying to figure out what mod was causing immersive portals to crash I also have Pluto installed, can confirm this happens to me too.

I wonder if this had been the mod screwing me over from using immersive portals.

**Comment by Nick1st** [comment] 2023-04-06 16:38
Duplicate of #18

**Closed as not planned by Nick1st** 2023-04-06 16:38 UTC
Labels: bug, duplicate, Mod Compatibility
